# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/seijiro/GoogleDrive/code/C:C++/myThe-Modern-Cpp-Challenge/libs/curlcpp/CMake/curlcppConfig.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/seijiro/GoogleDrive/code/C:C++/myThe-Modern-Cpp-Challenge/libs/curlcpp/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/seijiro/GoogleDrive/code/C:C++/myThe-Modern-Cpp-Challenge/libs/curlcpp/src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindCURL.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.13.4/share/cmake/Modules/SelectLibraryConfigurations.cmake))

/Users/seijiro/GoogleDrive/code/C:C++/myThe-Modern-Cpp-Challenge/build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -H/Users/seijiro/GoogleDrive/code/C:C++/myThe-Modern-Cpp-Challenge -B/Users/seijiro/GoogleDrive/code/C:C++/myThe-Modern-Cpp-Challenge/build
