# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/seijiro/GoogleDrive/code/C:C++/myThe-Modern-Cpp-Challenge/libs/ZipLib/extlibs/lzma/CMakeLists.txt))

/Users/seijiro/GoogleDrive/code/C:C++/myThe-Modern-Cpp-Challenge/build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -H/Users/seijiro/GoogleDrive/code/C:C++/myThe-Modern-Cpp-Challenge -B/Users/seijiro/GoogleDrive/code/C:C++/myThe-Modern-Cpp-Challenge/build
